language: node_js

node_js:
  - "0.10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS sqldown;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database sqldown;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS sqldown;'; fi"

env:
  - COMMAND=test
  - DB=mysql COMMAND=test
  - DB=postgres COMMAND=test
  - COMMAND=browser

script: npm run $COMMAND